### ISSUE TITLE
Reddit login button won't work after calling action sheet on WKWebView

### ISSUE THREAD

**Issue by ShingoFukuyama** [AgileBits/onepassword-app-extension#179] opened 2015-02-28 04:49 UTC
Filling out manually, the issue won't happen.
But once 1password action sheet called, the button won't respond. 

Below ViewController code can reproduce the issue.

```objc
#import "ViewController.h"
#import <WebKit/WebKit.h>
#import "OnePasswordExtension.h"

@interface ViewController ()

@property (nonatomic, strong) WKWebView *webView;

@end


@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    _webView = [[WKWebView alloc] initWithFrame:self.view.bounds];
    [self.view addSubview:_webView];
    
    NSString *urlString = @"https://www.reddit.com/login.compact";
    NSURL *url = [NSURL URLWithString:urlString];
    NSURLRequest *request = [NSURLRequest requestWithURL:url];
    [_webView loadRequest:request];
    
    // Call one password extension in a few seconds after launch
    __block typeof(self) self_ = self;
    NSTimer *timerA = [NSTimer timerWithTimeInterval:6.0
                                              target:[NSBlockOperation blockOperationWithBlock:^{

        [[OnePasswordExtension sharedExtension] fillLoginIntoWebView:self_.webView forViewController:self_ sender:self_ completion:^(BOOL success, NSError *error) {
            
        }];
        
    }] selector:@selector(main) userInfo:nil repeats:NO];
    [[NSRunLoop mainRunLoop] addTimer:timerA forMode:NSRunLoopCommonModes];
}

@end
```

Same as UIWebView.

**Comment by radazzouz** [comment] 2015-02-28 20:59
Hi @ShingoFukuyama,

Thanks for taking the time to write in :+1: 

I just tested tested your sample code by copy/pasting it in **ACME Browser**'s `viewDidLoad` and I couldn't reproduce the issue that you are describing.

Could you please send us more information about your issue? A sample project would be very appreciated :smile:  

I look forward to your reply!

Have a great weekend!

**Comment by ShingoFukuyama** [comment] 2015-03-01 06:07
Thank you for testing.

Still, I tried to build `WebView Demo for iOS` in this repository with no change, and run it on a device.

1. open `https://www.reddit.com/login.compact`
2. tap 1password icon at the top left of the header
3. tap `Cancel` or fill out the form
4. tap `login` button on the web page

Usually, a loading icon appears at the right of the button to proceed with the process by tapping the button or Go key on the software keyboard. I guess the form's submit event is somehow disabled.

![issue_1p](https://cloud.githubusercontent.com/assets/2087334/6429644/54c0c08c-c024-11e4-95e4-e55a93865287.png)

**Comment by radazzouz** [comment] 2015-03-01 18:05
Hi @ShingoFukuyama,

Thanks for getting back to us with detailed steps to reproduce :wink: 

You are right, after the 1Password extension fills the form one cannot submit it by tapping on the `login` button. However, if you manually copy and paste the username and password you can successfully login. 

So I just opened an internal bug (OPX-858) to investigate whether there's something we can do about the Reddit login form on our end.

Does this issue only happen with `https://www.reddit.com/login.compact` or does it happen on other sites too?

In the meantime, I am closing this as it's not an **App Extension API** bug.

Enjoy the rest of your Sunday :smiley:

**Closed by radazzouz** 2015-03-01 18:05 UTC
Labels: under investigation

**Comment by ShingoFukuyama** [comment] 2015-03-07 03:29
As far as I know, the behavior only occurs on Reddit (desktop and mobile view). 
Thank for taking care of it :+1:
