### ISSUE TITLE
Retrieved password is stripped of space characters

### ISSUE THREAD

**Issue by mattdelves** [AgileBits/onepassword-app-extension#164] opened 2015-02-04 04:49 UTC
When integrating 1password into an app, I'm seeing the case whereby a password stored in 1password that contains a space character will not have that character in it when returned from 1 password.

When looking at the desktop 1password app, the app is correctly displayed with the space.

When looking at the mobile 1password app, the app is incorrectly displayed without the space.

This then causes a problem as the extension will grab the wrong value.

Thanks,
Matt

**Comment by radazzouz** [comment] 2015-02-04 16:23
Hi @mattdelves,

Thanks for taking the time to write in :+1: 

I am using **ACME** and **ACME Browser** from the master branch and **1Password 5.2 for iOS**. I am also using **1Password 5.1 for Mac** and passwords with spaces in them fill just fine.

Please make sure that you are using the most recent versions of **1Password** and that you are using the latest version **1Password App Extension API** from master and not from the `1.1.0` tag. Since we recently had a fix in our filling logic for `kUTTypeAppExtensionFillWebViewAction` (see PR #144) that is post the `1.1.0` release.

If you can still reproduce the issue after make sure that everything is up-to-date, please send us more information on how we can reproduce it in **ACME** or **ACME Browser**.

Looking forward to your reply :smile: 

Cheers!

**Comment by radazzouz** [comment] 2015-02-24 14:17
Closing this issue as we can no longer reproduce it with the latest versions of 1Password and of the App Extension API.

**Closed by radazzouz** 2015-02-24 14:17 UTC
