### ISSUE TITLE
Extension broken on iOS 10?

### ISSUE THREAD

**Issue by kdawgwilk** [AgileBits/onepassword-app-extension#345] opened 2016-09-08 00:33 UTC
every time I try and launch the extension it asks for password, or TouchID and then crashes I think?  It just closes before you can even pick a login.  Sometimes it just freezes with the vault icon and doesn't even prompt for a password or TouchID

**Comment by radazzouz** [comment] 2016-09-08 14:02
Hi @kdawgwilk,

Thanks for taking the time to write to us!

Does this behaviour happen when you launch the extension in Safari or a/your thrid party app?

Are you using the latest version of iOS 10 GM?

Can you please reboot your device and see it the problem persists?

I look forward to your reply!

**Comment by kdawgwilk** [comment] 2016-09-08 17:32
This happens when launching the extension from 3rd party app built with Xcode 7.3.1 on iOS 10 GM and still happens after reboot.  I also tested the same app on a device running iOS 9.3.5 and it works great!

**Comment by radazzouz** [comment] 2016-09-08 17:51
Thanks for clarifying this for me, @kdawgwilk!

Can you please send me a diagnostic report to support+appex@agilebits.com from your device running iOS 10 GM? Please make sure that you mention this issue in the email.

Please keep me posted!

**Comment by radazzouz** [comment] 2016-09-08 18:01
Also, can you please test on your device running iOS 10 GM if you can reproduce this issue on another third party app mentioned in our [Apps ❤ 1Password page](https://blog.agilebits.com/1password-apps/)?

Thanks!

**Comment by kdawgwilk** [comment] 2016-09-08 22:25
@radazzouz I tested with the Intercom app and it works great on iOS 10 GM...what could be wrong on our end with it working on iOS 9 but not 10 GM?

**Comment by radazzouz** [comment] 2016-09-08 22:39
There are several things that could be wrong on your end. It is hard for me to tell without more info.

Could you please send me a TestFlight invite to rad.at.agilebits.com so I can look at it on my end?

Cheers!

**Comment by radazzouz** [comment] 2016-09-14 18:15
Hi @kdawgwilk,

I'll be closing this issue, since so far it doesn't seem to be an App Extension API issue.

Please feel free to re-open it, if you find out otherwise.

Best!

**Comment by kdawgwilk** [comment] 2016-09-29 17:51
I think I have figured out where the problem might be occurring.  We use [Facebook Tweaks](https://github.com/facebook/Tweaks) and it basically takes over the window to detect a shake of the device while the app is open [described here](https://github.com/facebook/Tweaks#tweaks-ui).  Is there a way to workaround this issue?

**Comment by kdawgwilk** [comment] 2016-09-29 18:13
Never mind I tried removing the Facebook Tweaks and got the same results :(

**Comment by kdawgwilk** [comment] 2016-09-29 18:35
Here is a gif of what is happening in two scenarios:
 - The first scenario shows the extension launching and prompting for TouchID but then crashes as soon as it launches
- The second scenario show that it gets stuck before it prompts for TouchID and never continues so you have to cancel.

![1passwordfail](https://cloud.githubusercontent.com/assets/7799267/18967000/c863b272-8640-11e6-9632-663c0ef231fe.gif)

**Comment by gks** [comment] 2016-09-29 18:56
Hi @kdawgwilk 

Sorry that this issue continues to give you trouble.

Does this issue persist if you disable Touch ID in 1Password? You can do so in the 1Password app under **Settings** > **Security**. 

It'll require you type your Master Password in, but this is simply a test to see if we can learn more about the problem and how it behaves. 

I look forward to hearing how this works (or doesn't work) for you.

**Comment by kdawgwilk** [comment] 2016-09-29 19:13
@gks Thanks for the quick response!  I disabled TouchID and it worked great!

**Comment by gks** [comment] 2016-09-29 19:17
Hi @kdawgwilk 

Great! Rad, a colleague of mine who you were working with before, had spent a great deal of time on this one in the past to figure it out. 

According to him it is a very rare issue. The only other occurrence that we've seen was caused by dismissing the last modal view controller from the stack in the application delegate callbacks.

Here's what happened:

* The Touch ID prompt is one of the most modal components that I've ever seen.
* Notice that after you unlock using Touch ID in the 1Password App Extension some of the `UIApplicationDelegate` callbacks (`applicationDidBecomeActive:`, `applicationWillEnterForeground:`, etc.)  fire up.
* Please make sure that you don't dismiss any modal view controller in these call backs. Strangely, in the other occurrence the 1Password App Extension was dismissed and it was causing it to crash.

Let me know if that helps get things back on track for you.

**Comment by kdawgwilk** [comment] 2016-09-29 19:20
Thanks! I will look into this and see what I can find 👍

**Comment by kdawgwilk** [comment] 2016-09-29 19:39
Interesting enough I didn't have any of those methods in my AppDelegate but as I looked deeper I found that I was subscribed to:
```
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(appWokeUp), name: UIApplicationDidBecomeActiveNotification, object: nil)
```
In my LoginViewController that was checking auth and logging in automatically (along with resetting views 👎 ).  Thanks again for the help!

**Comment by gks** [comment] 2016-09-29 19:53
My pleasure! Glad to hear you've gotten things cleared up now.

Thank you for adding 1Password support to you application! If we can ever help in the future don't hesitate to let us know!

**Closed by gks** 2016-09-29 19:53 UTC
Labels: under investigation
