### ISSUE TITLE
Navigation Bar Color Issue

### ISSUE THREAD

**Issue by wlisac** [AgileBits/onepassword-app-extension#256] opened 2015-09-04 16:43 UTC
The navigation bar changes to a standard OnePassword color after logging in, but our custom navigation button color does not change, which makes it hard to read "Cancel" in our case.

I would expect the navigation bar and the navigation button to either both change colors to the standard color or both stay at the custom color defined by our app.

Here is a [video](http://lisac.org/servicenow/onepasswordnavbar.mov) to make this easier to see the issue.

![img_0014](https://cloud.githubusercontent.com/assets/2246764/9689205/5c4f7322-52e9-11e5-91be-3d18e08f09ef.PNG)

**Comment by radazzouz** [comment] 2015-09-04 17:27
Thanks for taking the time to write to us, @wlisac :+1:

This issue is a duplicate of #205, so I will close it as such.

Please refer to my [comment](https://github.com/AgileBits/onepassword-app-extension/issues/205#issuecomment-99121652) on that issue for the related rdars and for the workaround.

Hope that this helps :wink:

Have an amazing weekend!

**Closed by radazzouz** 2015-09-04 17:27 UTC
Labels: duplicate

**Comment by wlisac** [comment] 2015-09-04 17:37
I'm not sure this is the same issue, but it may be related.

"The 1Password extension respects the appearance of your view controller navigation bar, but does not respect the preferredStatusBarStyle of your view controller."

This is not the behavior I'm seeing. 1Password stops respecting the navigation bar once the user has authenticated with 1Password. See the video above for details.

**Comment by radazzouz** [comment] 2015-09-04 17:57
Hi @wlisac,

> I'm not sure this is the same issue, but it may be related.

Yes, they are related :wink: 

> This is not the behavior I'm seeing. 1Password stops respecting the navigation bar once the user has authenticated with 1Password.

The workaround from my [comment](https://github.com/AgileBits/onepassword-app-extension/issues/205#issuecomment-99121652) on issue #205 will solve your problem too. It will force the 1Password extension to ”ignore” your app’s theme (`[UINavigationBar appearance]`).

I was able to reproduce it in **ACME**, our demo app.

**Before the workaround**

**Locked**
![](https://www.evernote.com/l/AVTojJ4hNvpILrNMgteFk9vKjb_HhzNqLmEB/image.png)

**Unlocked**
![](https://www.evernote.com/l/AVRSLZiVjPFP5oFXjAQETLbEIqGn2nbrMpsB/image.png)

**After the workaround**

**Locked**
![](https://www.evernote.com/l/AVRxQvriN_ZIEqxCntCxyPo2hoqYRcYvHEgB/image.png)

**Unlocked**
![](https://www.evernote.com/l/AVTHyk_Kr9JMRr06oIfaGBKxlauWKTJN_6wB/image.png)

> See the video above for details.

I did watch your video before replying the first time. Sorry I didn't mention it in the initial reply.

Let me know if this helps :smiley: 

Cheers!

**Comment by wlisac** [comment] 2015-09-04 18:06
Gracias. Thank you for your help!

**Comment by wlisac** [comment] 2015-09-04 18:06
Thank you for your help :)

**Comment by radazzouz** [comment] 2015-09-04 18:09
Thanks for letting me know that you've sorted it all out, @wlisac! :+1:
