### ISSUE TITLE
Version 1.5 breaks image loading via  -imageNamed:

### ISSUE THREAD

**Issue by Blackjacx** [AgileBits/onepassword-app-extension#248] opened 2015-08-26 13:13 UTC
Hi there,

I lost my onepassword button since you now create a bundle from the images. Please provide a macro that cares for loading the button image from the correct bundle so I doesn't need to care for the bundle name since it could change in future.

Thanks guys

**Comment by radazzouz** [comment] 2015-08-26 14:36
Hi @Blackjacx,

Am I right to assume that you are using CocoaPods? If so please note [resource bundles](http://guides.cocoapods.org/syntax/podspec.html#resources) are a new thing in CocoaPods and they recommed that we (library developers)  use them.

Here's how to obtain images from the resource bundles:

```objective-c
NSBundle *onepasswordExtensionResourcesBundle = [NSBundle bundleWithPath:[[NSBundle bundleForClass:[OnePasswordExtension class]]pathForResource:@"OnePasswordExtensionResources" ofType:@"bundle"]];
UIImage *image = [UIImage imageNamed:@"onepassword-button.png" inBundle:onepasswordExtensionResourcesBundle compatibleWithTraitCollection:nil];
[self.onepasswordSigninButton setImage:image forState:UIControlStateNormal];
```
I am also attaching this [sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip) which showcases the use of CocoaPods recource bundles in ACME.

> Please provide a macro that cares for loading the button image from the correct bundle so I doesn't need to care for the bundle name since it could change in future.

CocoaPods is one if several ways to use the **1Password App Extension API**, therefore we cannot add a CocoaPods-specific macro. If you feel strongly about the macro, we strongly suggest that you add it in your project.

This issue is a duplicate of #187 and #236. There are instructions and lenghty discussions in there spread across several comments. Therefore I am closing this one as a `duplicate`.

Hope that this helps :wink:

**Closed by radazzouz** 2015-08-26 14:36 UTC
Labels: duplicate, wontfix

**Comment by Blackjacx** [comment] 2015-08-26 15:59
kk thx :)

**Comment by radazzouz** [comment] 2015-08-26 15:59
:+1:
