### ISSUE TITLE
1passwordExtension and cocoapods 0.39 issue

### ISSUE THREAD

**Issue by jbbichon** [AgileBits/onepassword-app-extension#268] opened 2015-10-16 16:59 UTC
Hello Guys,

It seems that cocoapods 0.39 and 1PasswordExtension encounter some issue on a clean pod update

I check in the header path file and one is missing since I update to cocoapods 0.39 :

"${PODS_ROOT}/Headers/Public/1PasswordExtension/OnePasswordExtension"

the other one is still present but not recursive (${PODS_ROOT}Headers/Public/1PasswordExtension). it result in a crash when we try to build the project:

#import "OnePasswordExtension.h" file not found

Cordially,

Jb

**Comment by radazzouz** [comment] 2015-10-16 19:02
Hi @jbbichon,

Thanks for taking the time to write in :+1: 

I did see indeed on the Twittersphere reports about missing headers after updating to CocoaPods 0.39.0. However, I couldn't reproduce it here locally and here's what I did:

* I updated to CocoaPods 0.39.
* I used the attached [sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip) and I "cleaned" the project by trashing the following files and directories:
![](https://www.evernote.com/l/AVRKuMvyt3tIb7384ADgJYoRExpWuQcoqsoB/image.png)
* I ran `pod install`

As a result the demo app, **ACME** built and ran just fine.

Could you please try and reproduce the issue using my sample project?

Cheers!

**Comment by jbbichon** [comment] 2015-10-17 09:41
mmm...I see, we are not using "use_frameworks!" command in our podfile and it fail (some other project just don't support it).

I made a pull request with a small fix that seems to work with both mode (with and without "use_frameworks!"). please have a try ;)

Cheers!

**Comment by radazzouz** [comment] 2015-10-17 18:25
Thanks again @jbbichon for the detailed steps to reproduce :+1: 

I confirm that PR #270 fixed it. We just shipped version `1.6.3` of the 1Password App Extension API with this fix. So you can point to master of to the `1.6.3` tag,

Closing this issue.

Bon weekend! :wink:

**Closed by radazzouz** 2015-10-17 18:25 UTC
Labels: fixed
