### ISSUE TITLE
Ignore `www.` when looking up URLs 

### ISSUE THREAD

**Issue by PadraigK** [AgileBits/onepassword-app-extension#207] opened 2015-05-07 05:21 UTC
If a user is trying to log in to `www.newsblur.com` and their 1Password record is for `http://newsblur.com`, it won't be located using `fillLoginIntoWebView:forViewController:sender:completion:` — if the 1Password extension always trimmed off the `www.` when looking up the record in 1Password, it would find it either way.

**Comment by radazzouz** [comment] 2015-05-07 13:57
Hi @PadraigK,

Thanks for taking the time to write in :smile: 

I just tested it using the latest version of 1Password from the App Store (version  5.4.1) and by using our demo app, **ACME Browser** right from the master branch.

So here's what I did to test it:

* I had a Login in 1Password with a single URL, which was `http://newsblur.com`

![](https://www.evernote.com/l/AVRkF1mDsjBJm4wDBLQ7DXXHBbhx1SjJt_UB/image.png)

* I went to `www.newsblur.com` in **ACME Browser**.
* Called the 1Password extension and I got this.

![](https://www.evernote.com/l/AVT_fq-1MX5KnYgO774PBjsfPs-SUSvWKRQB/image.png)

* After tapping on my `Newsblur` login it filled correctly.

BTW, **ACME Browser** no longer uses `fillLoginIntoWebView:forViewController:sender:completion:` it uses a newly added method which is very similar to it: `fillItemIntoWebView:forViewController:sender:showOnlyLogins:completion:`

Am I missing something? Can you please make sure that you are using the latest version of 1Password and of the App Extension API (master not the `1.2` tag)?

I look forward to your reply :wink: 

Cheers!

**Comment by PadraigK** [comment] 2015-05-09 00:04
Hi @radazzouz,

You're completely right, it works correctly. I had assumed from this conversation that there was a problem, but now that I try, I can't recreate it: https://twitter.com/1Password/status/592736692194385921

Thanks so much for your help,

All the best,

Padraig.

**Comment by radazzouz** [comment] 2015-05-09 00:09
Hey @PadraigK,

I'm glad that it works and that I was able to help :smile: 

I will close this issue for now as `cannot reproduce`. Please do let me know if there's anything else I can do to help :wink: 

Have a great weekend!

Best,

Rad

**Closed by radazzouz** 2015-05-09 00:09 UTC
