### ISSUE TITLE
[KNOWN ISSUE] Resources and resource_bundle issues when using CocoaPods 1.0.0 Betas

### ISSUE THREAD

**Issue by mergesort** [AgileBits/onepassword-app-extension#187] opened 2015-03-23 23:34 UTC
I'm using the Cocoapods for 1Password. It just started not being able to copy over the resources, generating this error now.

```
~/Documents/Projects/iOS/my_project/1PasswordExtension/1Password.xcassets: warning: Failed to read file attributes for "~/Documents/Projects/iOS/my_project/1PasswordExtension/1Password.xcassets"
    Failure Reason: No such file or directory
/* com.apple.actool.compilation-results */

Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

The directory should actually be `~/Documents/Projects/iOS/my_project/Pods/1PasswordExtension/1Password.xcassets` though, not 
`~/Documents/Projects/iOS/my_project/1PasswordExtension/1Password.xcassets`

Any thoughts?

Thanks for the library!

**Comment by radazzouz** [comment] 2015-03-24 14:38
Hi @mergesort,

Thanks for taking the time to write to us :+1:

Similar issues have been reported in issues #180 and #181. 

Please try and delete your derived data and try and use the master branch rather than the `1.1.2` tag. Your podfile should look similar to this:

```pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'
```
Hope that this helps :wink: 

Cheers!

**Comment by taberrr** [comment] 2015-03-24 15:06
https://github.com/CocoaPods/CocoaPods/issues/1546#issuecomment-83795506

**Comment by mergesort** [comment] 2015-03-25 01:04
@radazzouz Oh, sorry, I looked through the open issues and didn't see it, didn't check the closed ones. I deleted derived data and switched to master, but no luck.

@taberrr I couldn't get that script to work, it's supposed to be run as /bin/sh, right? Keeps erroring out for me and won't compile.

**Comment by taberrr** [comment] 2015-03-25 02:20
@mergesort The @zygoat one? That actually goes in your Podfile. If you already have a similar `post_install do |installer|` loop in there, you'll need to combine 'em into one.

**Comment by erikackermann** [comment] 2015-03-25 22:53
@radazzouz you can also add this to your Podfile instead (bit more succinct):
`pod '1PasswordExtension', :head`

**Comment by ld0891** [comment] 2015-03-29 05:02
@radazzouz I encountered the same problem here, but switching to master branch didn't help.

**Comment by jtreanor** [comment] 2015-03-30 11:20
master, :head and the latest tag are also not working for me.

**Comment by radazzouz** [comment] 2015-03-30 13:07
Hi guys,

I assume that this is a CocoaPods issue ([#1546](https://github.com/CocoaPods/CocoaPods/issues/1546#issuecomment-86621371)). Is there anything we can do on our end to make sure that the resources are copied over properly?

Does @problame's [workaround](https://github.com/CocoaPods/CocoaPods/issues/1546#issuecomment-86621371) work fine for you guys?

Cheers!

**Comment by mergesort** [comment] 2015-03-30 16:00
@radazzouz I hadn't seen that solution, that worked for me. \o/
I'll wait for a more official fix, and use this in the mean time.

**Comment by mpanoff** [comment] 2015-03-30 23:46
Seeing this issue as well.

**Comment by radazzouz** [comment] 2015-03-30 23:56
Hi @mpanoff,

Can you please try the following steps to fix it? They worked for me:

1. Make sure that you are using CocoaPods 0.36.1
2. Clean the derived data (Both Clean and Clean Build folder) in **Xcode > Product > Clean**
3. Run `pod update`

Hope that this helps.

Best,

**Comment by mpanoff** [comment] 2015-03-31 00:23
Thanks for the quick reply. I tried all that. Didn't work. I need to investigate some more on our end. The `Failure Reason: No such file or directory` error I'm seeing is rather vague.

**Comment by mergesort** [comment] 2015-03-31 20:40
@mpanoff I'm getting this error now that I upgraded to 0.36.1, and can't compile my app. :cry:

**Comment by mpanoff** [comment] 2015-03-31 21:07
Yeah sadly 0.36.1 makes things worse. We reverted to previous version. :super sad:

**Comment by dmiedema** [comment] 2015-04-02 21:39
Updating to Cocoapods `0.36.3` and running a `pod update` fixed the issue for me

**Comment by radazzouz** [comment] 2015-04-02 22:58
Thanks for the heads up @dmiedema!

I will wait for more reports confirming that CocoaPods `0.36.3` fixes it and will close the issue.

**Comment by ld0891** [comment] 2015-04-06 04:10
Hi @radazzouz 
CocoaPods ```0.36.3``` didn't fix this issue in my case, but @problame's [workaround](https://github.com/CocoaPods/CocoaPods/issues/1546#issuecomment-86621371) did help.
I've tried cleaning my project and rebuilding it, removing ```1Password``` extension and re-adding it to my project in vain.
Seems modifying the shell script used by CocoaPods is the only way to fix it, currently.

**Comment by AliSoftware** [comment] 2015-04-07 16:18
@radazzouz Did you try migrating your `podspec` over using [`resource_bundles`](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles) instead of [`resources`](https://guides.cocoapods.org/syntax/podspec.html#resources) which is deprecated?

Not sure it will solve everything, but that's how we suggest to include resources in pods now, as it's better handled by Xcode

**Comment by radazzouz** [comment] 2015-04-08 15:48
Hi @AliSoftware,

Thanks for the suggestion :+1: 

Yes, I just replaced `resources` with `resource_bundles` in our `podspec` file in the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles)branch and I updated the `podfile` in my sample project as follows:

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'cocoapods-resource_bundles'
```

The result was: 

```NoMethodError - undefined method `each' for "1Password.xcassets":String```

However, if I revert back to `resources` instead of `resource_bundles` (switch back to master) it all works fine.

Here's how my `podfile` looks now:

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'
```

Note that I tested this with both version `0.36.1` and `0.36.3` of CocoaPods.

Hope that this helps :-D

Cheers!

**Comment by AliSoftware** [comment] 2015-04-08 17:40
@radazzouz resource_bundles is supposed to be a Hash ([see guides](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles)), not a string. That's why you got the `NoMethodError` on `String`.

**Comment by radazzouz** [comment] 2015-04-08 23:15
Hi @AliSoftware,

Thanks for clarifying :+1: 

I just updated the `podspec`file on the same branch ([cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles)) and did a `pod update` and everything works fine now.

I wonder if it works great for other folks too. So here was my setup:

* CocoaPods `0.36.3`
* Updated my in my podfile with `pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'cocoapods-resource_bundles'.
* Cleaned Xcode's derived data.
* Quit Xcode.
* Deleted the the `Podfile.lock` and the `Pods` folder (note that the 1Password App Extension API is the only Pod that I am using for my demo app).
* ran `pod update`.
* Relaunched Xcode.
* Ran my project.

Hope that this helps :wink:

**Comment by AliSoftware** [comment] 2015-04-09 17:55
Thanks for the tests @radazzouz 

Did you actually also confirm that your project can indeed access those resources from code once they have been integrated by CocoaPods? Are they still found by your `UIImage` calls?

**Comment by radazzouz** [comment] 2015-04-13 23:00
Good point @AliSoftware, I guess that the issue is still present because all `UIImage` instances that use images from the `1Password.xcassets` are `nil`. 

Here's a screenshot of the debugger:

![](https://www.evernote.com/shard/s340/sh/79a8dd94-02df-49b7-a2a7-6b17db2a330e/2bf0d05a9e6ea01f3414251418825009/deep/0/LoginViewController.m.png)

Any thoughts?

Thanks!

**Comment by AliSoftware** [comment] 2015-04-15 05:33
I bet your `onePasswordExtensionBundle` does not point to what you expect,

When using static libraries, your `OnePasswordExtension` class will ultimately be compiled within the main bundle (your ".app" itself), so that's where `onePasswordExtensionBundle` will points to. But your image will be embedded in a sub-bundle (named according to what you specified in your podspec for the `resource_bundle` key).

So instead you should point to `[[NSBundle bundleForClass:self] pathForResource:@"OnePassordExtensionResources" ofType:@"bundle"]` — provides you used something like `s.resource_bundles = { "OnePasswordExtensionResources" => ['onepassword-button.png', 'onepassword-button@2x.png'] }` in your `podspec`

**Comment by radazzouz** [comment] 2015-04-15 22:34
Hi @AliSoftware,

Thanks for the suggestion :+1: 

I haven't tried it yet, but I will soon.

Do we need to list each `png` file in our `xcassets` in our `pdspec`?

Thanks,

**Comment by radazzouz** [comment] 2015-04-16 14:15
Hi @AliSoftware,

I followed your instructions (see my latest [commit](https://github.com/AgileBits/onepassword-app-extension/commit/a62ab10b9f537a6c7d57938d1d117c49a50a96e1) on the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles) branch) and I couldn't get it work.

![](https://www.evernote.com/shard/s340/sh/1a704d7d-e1af-4393-a51d-e15a809a0fcd/c2ac13bf388f9b0976032ae39ab4e064/deep/0/LoginViewController.m.png)

Am I missing something?

Thanks!

**Comment by AliSoftware** [comment] 2015-04-16 15:07
Mmmh. Strange. Don't have time to look into it right know, but maybe you could start checking the file structure in the generated .app in the Finder to confirm that the `onePasswordExtensionBundlePath` actually exists?

**Comment by radazzouz** [comment] 2015-04-16 15:48
I confirm that the path exists in Finder for `OnePasswordExtensionResources.bundle`. However, when I perform "Show Package Contents" on it the directory/bundle is empty.

Thoughts?

**Comment by AliSoftware** [comment] 2015-04-16 16:25
When version of CP? master? 0.36.3? ali-xcassets? Other?

That's probably a bad side-effect of my refactors in my branch (which will be rewinded and need more work anyway)

**Comment by radazzouz** [comment] 2015-04-16 16:28
Hi @AliSoftware,

Thanks for being so quick with your replies :smile: 

CocoaPods 0.36.3. I simply used `sudo gem install cocoa pods`

Thank you!

**Comment by mergesort** [comment] 2015-05-05 14:22
@radazzouz Is this considered closed? Still having issues with it, even with the newest Cocoapods updates that seemingly resolved resource issues.

**Comment by radazzouz** [comment] 2015-05-05 14:32
Hi @mergesort,

No, it's not considered as closed. This issue is still under investigation. We are trying to figure out if there's something that we can do on our side to fix it.

Have you tried the steps from this [previous comment](https://github.com/AgileBits/onepassword-app-extension/issues/187#issuecomment-91064605) of mine? Do they work?

Thanks!

**Comment by radazzouz** [comment] 2015-05-05 16:41
Hi @mergesort,

I just pushed a change to the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles) branch.

Can you please update your `Podfile` as follows?

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'cocoapods-resource_bundles'
```

Also please make sure that you use the assets in this fashion:

```objective-c
- (void)viewDidLoad {
	[[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];
	[self.view setBackgroundColor:[[UIColor alloc] initWithPatternImage:[UIImage imageNamed:@"login-background.png"]]];
	[self.onepasswordSigninButton setHidden:![[OnePasswordExtension sharedExtension] isAppExtensionAvailable]];

	NSBundle *onepasswordExtensionResourcesBundle = [NSBundle bundleWithPath:[[NSBundle bundleForClass:[self class]]pathForResource:@"OnePasswordExtensionResources" ofType:@"bundle"]];
	UIImage *image = [UIImage imageNamed:@"onepassword-button.png" inBundle:onepasswordExtensionResourcesBundle compatibleWithTraitCollection:nil];
	[self.onepasswordSigninButton setImage:image forState:UIControlStateNormal];
}
```

You can also download my sample project from [here](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip) to test it out if you wish.

Please let me know how it goes. 

// cc: @AliSoftware 

Cheers!

**Comment by mergesort** [comment] 2015-05-06 16:27
@radazzouz I checked out the sample project, and I have no clue as to why it's not working for me. 
I pointed the podfile at that branch, and ended up with the correct resources.
![](https://cloud.githubusercontent.com/assets/716513/7497820/d9e04144-f3ea-11e4-9089-a71723bc65a1.png)

I copied the code directly from yours (changing the image used, but also with your image used, with .png at the end and without), and the button still doesn't show up (on a device with 1Password installed), the image after reading from the bundle is still nil.

![code](https://cloud.githubusercontent.com/assets/716513/7497842/f296458a-f3ea-11e4-9fed-3c4201ef955b.png)

![lldb](https://cloud.githubusercontent.com/assets/716513/7497891/311f4572-f3eb-11e4-8ddd-2307868b45db.png)

**Comment by radazzouz** [comment] 2015-05-06 16:34
Hi @mergesort,

Thanks for the quick response! Sorry to hear that it did not work for you. This very strange indeed! 

Is `onepasswordExtensionResourcesBundle` `nil` too? If it isn't, what happens if you change `onepassword-button-light` to `onepassword-button-light.png`?

Any thoughts @AliSoftware ?

Thanks!

**Comment by mergesort** [comment] 2015-05-06 18:33
@radazzouz Should have noticed that, yep, the bundle is nil.

**Comment by radazzouz** [comment] 2015-05-06 19:37
@mergesort, you may want to try and change the `self` to another class name in `NSBundle *onepasswordExtensionResourcesBundle = [NSBundle bundleWithPath:[[NSBundle bundleForClass:[self class]]pathForResource:@"OnePasswordExtensionResources" ofType:@"bundle"]];`

Hope that this helps :wink:

**Comment by tapi** [comment] 2015-05-06 19:42
Since the assets and classes should be in the same bundle you could even shorten that to NSBund

**Comment by radazzouz** [comment] 2015-05-06 19:51
@tapi thanks for chiming in :+1: 

I just changed it in my [sample app](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip) to both `NSBundle *onepasswordExtensionResourcesBundle = [NSBundle bundleForClass:[OnePasswordExtension class]]` and `NSBundle *onepasswordExtensionResourcesBundle = [NSBundle bundleForClass:[self class]]` and the image was `nil`. Notice that the bundle was never `nil` on the `UIImage` was in both instances.

![](https://www.evernote.com/l/AVQbf6AbJb5ES4kElgHUhYrUTTCo3QgcTS8B/image.png)

![](https://www.evernote.com/l/AVQbf6AbJb5ES4kElgHUhYrUTTCo3QgcTS8B/image.png)

I hope that @AliSoftware can shed some light on this.

**Comment by tapi** [comment] 2015-05-06 19:58
Just noticed that no one has mentioned wether or not they were using frameworks with Cocoapods.

**Comment by radazzouz** [comment] 2015-05-06 20:31
Good point @tapi! I was not using frameworks in the sample app. Meaning that we don't have the `use_frameworks` in the `Podspec` in the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles) branch.

**Comment by tapi** [comment] 2015-05-06 20:32
`use_frameworks` is a podfile directive not a pod spec one ;)

**Comment by radazzouz** [comment] 2015-05-06 20:36
Thanks @tapi! Always mix those two up :wink: Corrected my previous comment!

**Comment by mergesort** [comment] 2015-05-07 14:42
@radazzouz @tapi This is with `use_frameworks` and changing `self` to `OnePasswordExtension` fixed it!

**Comment by tapi** [comment] 2015-05-07 15:01
👍🏻😎

**Comment by radazzouz** [comment] 2015-05-07 15:25
@tapi thanks for the suggestion!

@mergesort I am really glad that you've got it all sorted out!

I just added the `use_frameworks!` directive to my `Podfile` and I've got linker error. Before adding it I was simple using `#import "OnePasswordExtension.h"`. What should I import now?

Thanks!

**Comment by radazzouz** [comment] 2015-05-16 00:52
YAY! It works now. Here's what I did:

1. Manually cleaned my projects configurations ( Project > Info > Configurations )

![](https://www.evernote.com/l/AVSN2zr7jVFEYI-2LASrr4R1-UtNTYu25BcB/image.png)

2. Manually cleaned my target's Build Phases

![](https://www.evernote.com/l/AVT0guZ0FupNVrFdXZSVx0Nb_Fd9nuY-M0EB/image.png)

3. Added `use_frameworks!` to my `Podfile`

4. Ran `pod install`

Questions: 

1. If we merge the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles) branch to master and release an update, what steps are required for all developers to access our resources when using CocoaPods? 

2. Is it documented somewhere so we can point our users to it? 

3. Is `use_frameworks!` required or optional?

4. Do all developers who use CocoaPods need to update to the latest version of CocoaPods?

Have an amazing weekend!

**Comment by dmyers** [comment] 2015-07-15 02:00
:+1:

**Comment by radazzouz** [comment] 2015-07-15 13:29
@dmyers, if you wish to test the the new `use_frameworks!` feature using CocoaPods, all you need to do is to point your pod file to the [cocoapods-resource_bundles](https://github.com/AgileBits/onepassword-app-extension/tree/cocoapods-resource_bundles) branch which is being kept in sync with master.

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'cocoapods-resource_bundles'
```

However, if you simply want to use the **1Password App Extension API** in your Swift project, please take a look at our Swift demo apps. They are available in separate branches:

**Swift 1.2**

[new/swift-demo-apps](https://github.com/AgileBits/onepassword-app-extension/tree/new/swift-demo-apps)

**Swift 2.0 (requires Xcode 7)**

[swift2.0](https://github.com/AgileBits/onepassword-app-extension/tree/swift2.0)

Let me know if this helps :smiley:

**Comment by radazzouz** [comment] 2015-07-22 21:10
Merged PR #235, the change is now on `master`. If you wish to test it, please make sure that you point to `master` in your `Podfile`.

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'
```

**Comment by jhoughjr** [comment] 2015-12-07 02:52
I'm seeing this issue for Info.plist on version 0.39

**Comment by radazzouz** [comment] 2015-12-07 14:51
Which `Info.plist` are you referring to, @jhoughjr ? In our `podspec` we do not import/copy any `Info.plist` in our [resource_bundles](https://github.com/AgileBits/onepassword-app-extension/blob/master/1PasswordExtension.podspec#L29).

**Comment by georgbachmann** [comment] 2016-02-25 07:54
Just had the same issue after updating to CocoaPods 1.0 beta 4 :( any suggestions? None of the above worked for me :(

**Comment by radazzouz** [comment] 2016-02-25 15:34
Hi @georgbachmann,

I think that you are experiencing a different issue. See https://github.com/CocoaPods/CocoaPods/issues/4872.

I worked around it by adding "1PasswordExtension" to `install_resource` from the CocoaPods-generated `Pods-YOUR_PROJECT-resources.sh` file.

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/1PasswordExtension/OnePasswordExtensionResources.bundle"
fi
```

Please let me know if it works for you.

Best,

**Comment by georgbachmann** [comment] 2016-02-25 15:48
Thx... looks good!

**Comment by radazzouz** [comment] 2016-02-25 15:48
:+1:

**Comment by JimVanG** [comment] 2016-03-15 06:17
I'm still facing this issue:
```
~/Library/Developer/Xcode/DerivedData/PROJECT-bznrqrgtuchrqoevbthnrinwqbji/Build/Products/Debug-iphoneos/1PasswordExtension/OnePasswordExtensionResources.bundle: No such file or directory
```

I've tried adding the workaround to my `Pods-PROJECT-resources.sh` file but with no luck. Is there any other workaround or fix? 

Where exactly do I put the workaround in my `Pods-PROJECT-resources.sh`?

**Comment by radazzouz** [comment] 2016-03-15 18:52
Hi @JimVanG,

I assume that you are using CocoaPods 1.0.0 Beta 6. The workaround used to work for 1.0.0 Beta 4. I just tried to apply the same workaround and it doesn't seem to work.

I noticed that https://github.com/CocoaPods/CocoaPods/issues/4872 was closed, but I also found the recently opened https://github.com/CocoaPods/CocoaPods/issues/5034. So the CocoaPods team seems to be aware of it.

For now, I believe that the only workaround is to revert back to the stable version of CocoaPods (0.39.0).

Thanks for integrating 1Password into your app.

Cheers!

**Comment by radazzouz** [comment] 2016-03-15 18:54
Reopening this issue for now.

**Comment by JimVanG** [comment] 2016-03-22 03:20
@radazzouz , I can also confirm that the workaround doesn't work for `1.0.0.beta.6`. I rolled back to `1.0.0.beta.5` and the problem went away. Thank you for your help!

**Comment by radazzouz** [comment] 2016-03-22 12:50
Thanks so much for confirming @JimVanG :+1: Hope that 1.0.0.beta.7 will fix it.

**Comment by radazzouz** [comment] 2016-04-18 13:55
I just updated to CocoaPods 1.0.0.beta.8 and the issue seems to have been resolved by the recent update.

I tested with both Objective-C and Swift based projects and with and without `use_frameworks!` in the Podfile.

Closing this issue for now.

Thank you all for helping find this issue.

**Closed by radazzouz** 2016-04-18 13:55 UTC
