### ISSUE TITLE
iPhone 6 iOS 8.1 TouchID doesn’t work

### ISSUE THREAD

**Issue by PawelDecowski** [AgileBits/onepassword-app-extension#132] opened 2014-10-30 21:57 UTC
Hi,

I’ve implemented the integration as per the readme file. It sometimes works to the point where it shows 1password screen with an option to scan fingerprint or enter master password. But sometimes it only shows the 1password background and stops there. The only thing I can do is tap cancel and go back to my app.

On the occasions that it does show me the option to scan fingerprint, when I do, it goes back to my app immediately (without listing any passwords) and doesn’t execute any code in `completion` (I placed a NSLog at the top and it doesn’t log anything).

If, instead of scanning fingerprint, I choose to enter master password, it works like intended.

Thanks,
Pawel

**Comment by radazzouz** [comment] 2015-01-27 14:49
Hi @PawelDecowski,

We just released 1Password 5.2 for iOS and we couldn't reproduce this crash in Mobile Safari, ACME or ACME Browser. Therefore I am closing this issue.

Feel free to re-open this issue if you can still reproduce it and please send us sample code (make changes to ACME or ACME Browser in order to reproduce it) so we can squash it down.

Cheers!

**Closed by radazzouz** 2015-01-27 14:49 UTC

**Comment by PawelDecowski** [comment] 2015-01-27 14:50
Thanks @radazzouz. I will test it when I get a chance.

**Comment by radazzouz** [comment] 2015-01-27 14:52
:+1:
