### ISSUE TITLE
Crash call this method from actionsheet - (IBAction)fillUsing1Password:(id)sender iPad

### ISSUE THREAD

**Issue by tikamchandrakar18** [AgileBits/onepassword-app-extension#122] opened 2014-10-15 14:57 UTC
Calling this method from UIactionsheet .app get chash
[self  fillUsing1Password:actionsheet];

- (IBAction)fillUsing1Password:(id)sender

**Comment by radazzouz** [comment] 2015-01-27 14:35
Closing this issue due to the lack of details. Please re-open if you have more information about how to reproduce it.

Thanks!

**Closed by radazzouz** 2015-01-27 14:35 UTC
