### ISSUE TITLE
Xcode 8.1 Cocoapods OnePasswordExtensionResources.bundle bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by kgellci** [AgileBits/onepassword-app-extension#357] opened 2016-10-27 01:04 UTC
Updated from Xcode 8.0 to 8.1 and the project will not compile because of the following error:

.../Debug-iphonesimulator/OnePasswordExtensionResources.bundle: bundle format unrecognized, invalid, or unsuitable

Tried deleting derived data, cleaning, etc.  On version 1.8.4'

Edit:  This is only happening when running on simulator, running on device works fine.

**Comment by gks** [comment] 2016-10-27 15:21
Hi @kgellci 

I have a project for one of our sample projects that is setup to use Cocoapods. I've downloaded the Xcode 8.1 GM from the 24th. I've deintegrated, then did the `pod install` dance just to kick everything in the shorts. 

The project seems to build just fine over here for me. So I don't think this is an Xcode 8.1 issue so much as a project configuration problem or needing to dance with Cocoapods a bit. It seems to require this type of thing more often than it should. Could you try deintegrating and then reinstalling your pods? I'm wondering if something is simply unhappy for you due to that.

**Comment by kgellci** [comment] 2016-10-27 15:31
Thanks, I had a feeling it may have been a project related issue since I did not see anyone else with this issue.  I will work through it on the weekend, switched back to 8.0 for now to release.

**Comment by gks** [comment] 2016-10-27 18:15
Hi @kgellci 

If you can recreate the problem in a sample project that would definitely be helpful. My gut tells me it's a project configuration issue, but that doesn't mean it is. I've been known to be wrong before ;)

Keep me in the loop though and if I can do anything to help I would be happy to lend a hand.

**Comment by pietropizzi** [comment] 2016-10-28 14:21
Hey. I just ran into the exact same issue.

* Updated from XCode 8 to 8.1
* Works on device but not simulator

Did all the dances of cleaning, removing pods & re-installing. Was not able to solve it.

**Comment by gks** [comment] 2016-10-28 18:39
Hi @pietropizzi 

I have a sample project [here](https://com-agilebits-users.s3.amazonaws.com/kyle/appext/ACME%20CocoaPods.zip). Could you try running this with cocoa pods? 

* Unzip
* Run `pod install`
* Build and run in the simulator

Like I suggested to @kgellci this project works for me, but maybe I have something setup differently on my end that is making it work when it shouldn't.

**Comment by pietropizzi** [comment] 2016-10-31 09:17
I installed XCode 8 again after this did not work. Will upgrade and try and report back.

**Comment by pietropizzi** [comment] 2016-10-31 09:42
So I tried it with you project and it has exactly the same error. Here's my lockfile


<details>
  <summary>Podfile.lock</summary>

  ```
PODS:
  - 1PasswordExtension (1.8.4)

DEPENDENCIES:
  - 1PasswordExtension (from `https://github.com/AgileBits/onepassword-app-extension.git`,
    branch `master`)

EXTERNAL SOURCES:
  1PasswordExtension:
    :branch: master
    :git: https://github.com/AgileBits/onepassword-app-extension.git

CHECKOUT OPTIONS:
  1PasswordExtension:
    :commit: 1c5c512a31b5c714e06be6d98d56643336f214e8
    :git: https://github.com/AgileBits/onepassword-app-extension.git

SPEC CHECKSUMS:
  1PasswordExtension: 7cae06bcd599e94318f1dd079de17dbbb66507a3

COCOAPODS: 0.39.0
 ```
</details>

Maybe it is the cocoa pods version? I am still using 0.39 as you can see.

**Comment by gks** [comment] 2016-10-31 15:40
@pietropizzi Definitely update CocoaPods. I'm using 1.0.1

```
$ pod --version
1.0.1
```

**Comment by kgellci** [comment] 2016-10-31 15:45
That could be it, I am on 0.38.2

**Comment by gks** [comment] 2016-10-31 15:48
Hi @kgellci 

If you could also try updating that'd be great, too. I'd love to hear if that solves the issues you're having.

**Comment by kgellci** [comment] 2016-10-31 19:04
@gks I have had lots of trouble updating, putting it off for now (too much time spent), hopefully someone else can chime in with the same issue confirming updating pods fixed it.

**Comment by pres** [comment] 2016-11-07 19:03
I had the same error on cocoapods 0.39.0.
Updating to 1.1.1 worked for me.

**Comment by gks** [comment] 2016-11-07 19:09
Hi @pres 

That's great to hear! I am fairly sure the issue is related to out of date cocoapods so I'm going to close this issue and if anyone finds that it does not fix things up we can perhaps re-open or investigate further.

**Closed by gks** 2016-11-07 19:09 UTC
Labels: question
