### ISSUE TITLE
with use_frameworks, image not available in client project's Interface Builder

### ISSUE THREAD

**Issue by haemi** [AgileBits/onepassword-app-extension#330] opened 2016-06-15 11:28 UTC
When including my pods with the use_frameworks! directive, I have to include the images via code the following way:

```
UIImage *image = [UIImage imageNamed:@"myImage" inBundle:[NSBundle bundleWithIdentifier:@"org.cocoapods.MyPod"] compatibleWithTraitCollection:nil];
```

That works perfect and as intended; but how can I reference an image in the client project (not! within a storyboard of the pod)? When I only enter the image name in Interface Builder the image is not shown...

**Comment by radazzouz** [comment] 2016-06-15 14:43
Hi @haemi,

Thanks for taking the time to write in. 👍 

I do not think that you can directly refer to the image from the bundle in a storyboard or a xib. However, you can add a `IBOutlet` and set the image to it in-code.

This issue seems to be a duplicate of #248. Please refer to [my comment](https://github.com/AgileBits/onepassword-app-extension/issues/248#issuecomment-135042466) for the full explanation and for the sample project. For now, I am closing this issue.

Please let me know if helps.

Cheers!

**Closed by radazzouz** 2016-06-15 14:43 UTC
Labels: question
